<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Write-up</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Write_up_files/libs/clipboard/clipboard.min.js"></script>
<script src="Write_up_files/libs/quarto-html/quarto.js"></script>
<script src="Write_up_files/libs/quarto-html/popper.min.js"></script>
<script src="Write_up_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Write_up_files/libs/quarto-html/anchor.min.js"></script>
<link href="Write_up_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Write_up_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Write_up_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Write_up_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Write_up_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Write_up_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Write_up_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<style>
  /* Reduce paragraph spacing */
  p {
    margin-top: 0.3rem !important;
    margin-bottom: 0.3rem !important;
  }

  /* Base body styling */
  body {
    font-size: 0.85rem;
    padding-left: 0.5rem !important;
    padding-right: 0.5rem !important;
  }

  /* Wider page */
  .quarto-container {
    max-width: 85% !important;
  }

  /* Smaller headings */
  h1 { font-size: 1.2rem !important; margin: 0.35rem 0 !important; }
  h2 { font-size: 1.05rem !important; margin: 0.3rem 0 !important; }
  h3 { font-size: 0.95rem !important; margin: 0.25rem 0 !important; }
  h4 { font-size: 0.85rem !important; margin: 0.2rem 0 !important; }
</style>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Write-up</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Authors: Tianle Chen, Sicheng Zhang, Zixuan Lin</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The April 2015 Nepal earthquake caused nearly 9,000 deaths and massive building damage, resulting in one of the largest post-disaster datasets ever collected. This project aims to predict&nbsp;<strong>damage_grade</strong>, an ordinal measure of building destruction (1 = low, 2 = moderate, 3 = severe). Accurate predictions help officials prioritize inspections and allocate reconstruction resources efficiently. Because large-scale manual inspections are costly and slow, we use machine-learning models that take building and geological features as inputs to automatically estimate damage severity.</p>
<p>There are numerous varables included in the dataset, below are the features distributions:</p>
<ul>
<li><p>Numeric Plots:</p>
<p><img src="images/clipboard-4054758307.png" class="img-fluid" width="216"><img src="images/clipboard-2895068315.png" class="img-fluid" width="208"></p></li>
<li><p>Categorical Plots:</p>
<p><img src="images/clipboard-2628711348.png" class="img-fluid" width="236"><img src="images/clipboard-4192401762.png" class="img-fluid" width="222"><img src="images/clipboard-891184747.png" class="img-fluid" width="219"></p></li>
</ul>
</section>
<section id="data-cleaning-feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-feature-engineering">Data Cleaning &amp; Feature Engineering</h2>
<p>Before modeling, we checked data quality and class balance. There were&nbsp;no missing values, so we focused on the imbalance in&nbsp;damage_grade, where only&nbsp;9.6%&nbsp;of buildings were labeled as grade 1. Because this could cause the models to overfit grades 2 and 3, we used&nbsp;SMOTE&nbsp;to oversample grade 1. After SMOTE, the class distribution became more balanced (about&nbsp;32.6% / 42.4% / 25%&nbsp;for grades 1–3). We then applied&nbsp;standard scaling&nbsp;to numerical variables to keep them on comparable ranges and reduce bias from differing scales.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>We evaluated several models to predict damage_grade, including a multinomial generalized linear model (GLM), Random Forest, CatBoost, and XGBoost.</p>
<p>For the multinomial GLM, we selected predictors based on variation and interpretability, removing invariant or near-constant features. The final set included variables reflecting structural and geographic characteristics (e.g., age, area_percentage, height_percentage, floor count, geo-levels, land_surface_condition, roof_type, and others). These features directly describe building attributes that plausibly affect damage severity.</p>
<p>For tree-based models (Random Forest, CatBoost, XGBoost), we used the full engineered feature set to maximize predictive power. Although these models sacrifice interpretability, they typically achieve higher accuracy because they aggregate information across many decision trees. Within Random Forest, we first fit a baseline model using the randomForest package, then used the faster ranger implementation to extract variable importance and to train larger forests efficiently. We also built a “top-30 features” version to test whether limiting the model to the most important predictors improved performance.</p>
<p>CatBoost, designed to handle categorical variables well, was trained using label-encoded predictors and tuned for tree depth, learning rate, and number of iterations.</p>
<p>For XGBoost, we conducted a small greedy hyperparameter search over max_depth and learning rate on SMOTE-balanced data and checked how each combination performed on a held-out test split, selecting the pairs that maximized balanced accuracy. Using that best tree depth and learning rate, we fit our XGBoost model with subsample = 0.8 and colsample_bytree = 0.8 to avoid overfitting.</p>
<p>As a robustness check, we also experimented with an Isolation Forest on numeric predictors to flag extreme outliers. Removing the top 2% most anomalous observations, we refit the full set of models to assess how sensitive results were to extreme cases.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>We evaluated all models on the 20% held-out test set from the SMOTE-balanced and scaled data. The table below summarizes overall accuracy, Cohen’s Kappa, and balanced accuracy for each model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table 1: Model Performance Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BalancedAccuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Multinomial GLM</td>
<td style="text-align: right;">0.564</td>
<td style="text-align: right;">0.282</td>
<td style="text-align: right;">0.626</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random Forest (randomForest)</td>
<td style="text-align: right;">0.789</td>
<td style="text-align: right;">0.670</td>
<td style="text-align: right;">0.826</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Random Forest (ranger, all vars)</td>
<td style="text-align: right;">0.805</td>
<td style="text-align: right;">0.695</td>
<td style="text-align: right;">0.837</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random Forest (ranger, top 30)</td>
<td style="text-align: right;">0.808</td>
<td style="text-align: right;">0.700</td>
<td style="text-align: right;">0.840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CatBoost</td>
<td style="text-align: right;">0.817</td>
<td style="text-align: right;">0.715</td>
<td style="text-align: right;">0.849</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">0.827</td>
<td style="text-align: right;">0.731</td>
<td style="text-align: right;">0.857</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>We are first showing results of the multinomial link GLM. It has an accuracy of 56.1%, which is only 6% higher than random guessing. It also has a Kappa of 0.28 and balanced accuracy around 62.6%. The confusion matrix shows that the GLM model tends to predict the “damage_grade = 2” class too often but struggles to correctly identify the other two classes. The reason GLM is not performing well in here is that the GLM mostly assumes straight-line effects and no rich interactions between variables, so it can’t pick up the complex patterns in the building-damage data.</p>
<p>The baseline Random Forest (Table 3) performs much better, reaching&nbsp;≈78.9% accuracy,&nbsp;Kappa ≈ 0.67, and&nbsp;balanced accuracy ≈ 82.6%. It substantially improves sensitivity for classes 1 and 3 compared with the GLM, though some confusion between damage_grades 2 and 3 remains.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table 2: GLM Stats (1,2,3 refers to damage grade)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(3)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.561</td>
<td style="text-align: right;">0.2772</td>
<td style="text-align: right;">0.6437</td>
<td style="text-align: right;">0.8179</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.8566</td>
<td style="text-align: right;">0.4132</td>
<td style="text-align: right;">0.994</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table 3: Random Forest Stats (1,2,3 refers to damage grade)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(3)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7888</td>
<td style="text-align: right;">0.6703</td>
<td style="text-align: right;">0.9264</td>
<td style="text-align: right;">0.8313</td>
<td style="text-align: right;">0.5376</td>
<td style="text-align: right;">0.9718</td>
<td style="text-align: right;">0.7629</td>
<td style="text-align: right;">0.9259</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>The ranger implementation (Table 4) improves things a bit further. With all predictors included, ranger reaches accuracy around 80.5% and balanced accuracy around 83.7%. When we restrict ranger to the top 30 most important predictors (Table 5), performance is almost unchanged with accuracy around 80.8%, balanced accuracy around 84.0%, and a slightly higher Kappa around 0.70). This implies that only a small group of key variables is doing almost all the work, so once those are in the model, adding all the other predictors doesn’t really help the accuracy any further.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table 4: Fast Implementation of Random Forests Stats with all predictors (1,2,3 refer to damage grade)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(3)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.8055</td>
<td style="text-align: right;">0.6954</td>
<td style="text-align: right;">0.9216</td>
<td style="text-align: right;">0.8656</td>
<td style="text-align: right;">0.5521</td>
<td style="text-align: right;">0.9788</td>
<td style="text-align: right;">0.7645</td>
<td style="text-align: right;">0.9405</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table 5: Fast Implementation of Random Forests Stats with top 30 predictors (1,2,3 refer to damage grade)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(3)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.808</td>
<td style="text-align: right;">0.6996</td>
<td style="text-align: right;">0.9227</td>
<td style="text-align: right;">0.8641</td>
<td style="text-align: right;">0.5633</td>
<td style="text-align: right;">0.9787</td>
<td style="text-align: right;">0.7699</td>
<td style="text-align: right;">0.9398</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>CatBoost (Table 6) outperforms the Random Forest models, achieving&nbsp;≈81.7% accuracy,&nbsp;Kappa ≈ 0.72, and&nbsp;balanced accuracy ≈ 84.9%. Actually, CatBoost handles the many categorical variables very well and can produce more even performance across the three damage_grade classes. The ROC curves show high AUC values for each class, indicating strong classification ability.</p>
<p>The greedy-tuned XGBoost model (Table 7) performs best overall, which has the best accuracy score among all models. The confusion matrix show very high sensitivity and specificity for damage_grade = 1 and 2, with a relatively lower but fairly reasonable sensitivity for damage_grade = 3. Also, ROC curves for XGBoost also show strong separation between damage_grade classes. Therefore, we used it to generate damage_grade predictions for all building ID in nepal_test.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table 6: Categorical Boosting Stats (1,2,3 refer to damage grade)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(3)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.8171</td>
<td style="text-align: right;">0.7151</td>
<td style="text-align: right;">0.9282</td>
<td style="text-align: right;">0.8557</td>
<td style="text-align: right;">0.6067</td>
<td style="text-align: right;">0.9836</td>
<td style="text-align: right;">0.791</td>
<td style="text-align: right;">0.9313</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table 7: Greedy Tuned XGBoost Stats (1,2,3 refer to damage grade)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity(3)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(2)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.8271</td>
<td style="text-align: right;">0.7308</td>
<td style="text-align: right;">0.928</td>
<td style="text-align: right;">0.8682</td>
<td style="text-align: right;">0.6261</td>
<td style="text-align: right;">0.9874</td>
<td style="text-align: right;">0.7989</td>
<td style="text-align: right;">0.9352</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>In total, our greedy-tuned XGBoost and CatBoost models outperforms the random forest models because boosting builds trees sequentially, where each tree is built focusing and correcting on the errors of the previous trees, instead of just averaging many independent bagged trees like in random forest. This usually allows us to identify more complex patterns in the data. In our case, XGBoost performed better than CatBoost, which is a little bit surprising because CatBoost is a newer gradient boosting algorithm that is usually very strong on data with many categorical variables. The reason is practically-driven instead of theoretical that we spent more efforts tuning XGBoost’s key hyperparameters, such as tree depth and learning rate, using greedy search, so it can adapt more closely to the patterns in the training data. However, our CatBoost model was run with mostly default settings and only light tuning, and thus did not reach the same level of accuracy as XGBoost. So this experience shows the importance of careful hyperparameter tuning and model comparison, and we should not assume that a more recent, advanced or fancy algorithm will automatically perform better.</p>
</section>
<section id="discussions" class="level2">
<h2 class="anchored" data-anchor-id="discussions">Discussions</h2>
<p>The greedy-tuned XGBoost model performance evaluated using overall accuracy on the held-out test data is 82.8%, and the balanced accuracy is 85.8%, which are both high and extremely satisfactory. The ROC curves of this model also shows excellent class separability, and we can see that AUC for damage grade 1 is 0.993, 0.908 for grade 2, and 0.912 grade 3, with a macro-AUC of 0.937.</p>
<p>We also observed some misclassifications, and the model mostly confuses between closeby classes. However, the minor misclassification is acceptable especially considering the complexity of real-world situations and likelihood of overfitting. In conclusion, the fitted model discriminates very well overall, as we can see from the sensitivity, specificity, etc. of every classes, showing that the model have the great potential to be practically used for real-world damagegrade prediction.</p>
<p>Also, it would be worthy to point out that we also tried some other methods including but not limiting to GLM, Random Forest, CatBoost, etc. The basic random forest method also yield to a very strong accuracy of around 80%, and so for interpretability purposes one could also use random forest to draw geological conclusions.</p>
<p><img src="images/Screenshot%202025-11-21%20at%2019.45.00.png" class="img-fluid" width="314"></p>
<p>After refitting all models after removing the potential outliers by Isolation Forest, the main performance metrics changed only slightly. The XGBoost model still had the best accuracy and balanced accuracy, and the relative ranking of models stayed the same. This suggests that our conclusions are not being mastered by a handful of extreme buildings/outliers, and that the original results based on the full SMOTE-balanced dataset are fairly robust.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>